### ISSUE TITLE
[1.19.2] Vanilla wood crafting tables (aside from Mangrove) are uncraftable.

### ISSUE THREAD

**Issue by Gemini04126** [852DuartePls/MoreCraftingTables#12]
Exactly as the title says. Tested with MCT v4.2.1, Forge v43.3.0, Minecraft v1.19.2.
Modded crafting tables are able to be crafted, i.e. Fir from BoP, but Oak, Dark Oak, Birch, Spruce, Acacia, Jungle, Crimson, and Warped are all uncraftable.

![image](https://github.com/852DuartePls/MoreCraftingTables/assets/8532523/20c15dce-5c2c-4522-ba59-7eccea8ab46e)
![image](https://github.com/852DuartePls/MoreCraftingTables/assets/8532523/4734d41d-d9ce-4633-8ce0-8dc303ecd4ed)
![image](https://github.com/852DuartePls/MoreCraftingTables/assets/8532523/6c7869b6-2519-4f53-a41f-975212c88d8b)
![image](https://github.com/852DuartePls/MoreCraftingTables/assets/8532523/a1da48f7-5af3-4e00-bfa5-2c3b5fd35185)
![image](https://github.com/852DuartePls/MoreCraftingTables/assets/8532523/02358726-55e8-4251-a562-caf764ffadf4)
![image](https://github.com/852DuartePls/MoreCraftingTables/assets/8532523/a9760cca-e437-4afc-a57f-623a875e0674)
![image](https://github.com/852DuartePls/MoreCraftingTables/assets/8532523/cd260f31-f698-4daa-a19e-cfce934d6706)
![image](https://github.com/852DuartePls/MoreCraftingTables/assets/8532523/3f34b6f9-b4d9-412c-af13-d1988ee0d059)
![image](https://github.com/852DuartePls/MoreCraftingTables/assets/8532523/39580164-2f04-47b0-a9a2-283cd15274ce)

**Comment by Gemini04126** [comment]
[mctb_fix.zip](https://github.com/852DuartePls/MoreCraftingTables/files/12775657/mctb_fix.zip)
Made a datapack to temporarily fix this, it just redefines the recipes in question.

**Comment by 852DuartePls** [comment]
I updated the file with the changes and did some tests, everything worked okay on my end and I uploaded it, let me know if the problem persists, thanks in advance

https://legacy.curseforge.com/minecraft/mc-mods/more-crafting-tables-for-forge/download/4777739

**Comment by Gemini04126** [comment]
It works, thanks!
