### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by Jadan1213** [852DuartePls/MoreCraftingTables#16]
Do you still have the source files for 1.20.1 MCTB vers 5.1.1?

**Comment by 852DuartePls** [comment]
Yes but i only can provide it via direct download [SOURCE - MCTB 1.20.1](https://www.mediafire.com/file/ps9f0s0up1iiwiv/SOURCE_-_MCTB_1.20.1.rar/file), you need java 17 to build it
