### ISSUE TITLE
[Suggestion] Add config to enable/disable mod compatibility

### ISSUE THREAD

**Issue by JuanPacoPedrodelaMar** [852DuartePls/MoreCraftingTables#20]
I would like this to be made due to the fact it is kinda annoying to search in creative "crafting table" and see a lot of variants of it, many of them from mods which you may have not installed. It is ok if you do not want to do it, I just wanted to give my thoughts about this.

**Comment by 852DuartePls** [comment]
It's a very good idea, i will see a way to implement it ^-^

**Comment by JuanPacoPedrodelaMar** [comment]
That would be awesome, thank you :)

**Comment by 852DuartePls** [comment]
Sorry for the delay, I was in exam period and just now I was able to resume this
The way I implemented it was like this 738c499dec60d0414bd26aea2799f547b0bd4089 and it should already be available for download in modrinth or curseforge

**Comment by JuanPacoPedrodelaMar** [comment]
That´s great, thank you :)
