### ISSUE TITLE
More wood types for compatibility with Abnormals Mods?

### ISSUE THREAD

**Issue by StygianEmperor** [852DuartePls/MoreCraftingTables#4]
The [TeamAbnormals](https://www.curseforge.com/members/teamabnormals/projects) mods seem pretty popular so I'm kind of surprised the wood types added by their biomes aren't covered by this. 

While I'm _pretty sure_ adding them is something I could do myself, I haven't totally figured out how Pull Requests work, so I'll try to cut down the work for you to the point where you mostly need to adjust some colors. I'll add a link to each mod that's at least compatible with 1.16.4 here and list the new wood types in each, with their respective "planks" textures.

- [Atmospheric](https://www.curseforge.com/minecraft/mc-mods/atmospheric)
  - Aspen 
![aspen_planks](https://user-images.githubusercontent.com/75293860/105848825-2a5e5580-5fa5-11eb-9279-43d8182c466e.png)
  - Grimwood
![grimwood_planks](https://user-images.githubusercontent.com/75293860/105848841-2e8a7300-5fa5-11eb-9745-77bf076359be.png)
  - Kousa
![kousa_planks](https://user-images.githubusercontent.com/75293860/105848852-31856380-5fa5-11eb-903e-1e2256a91b2f.png)
  - Morado
![morado_planks](https://user-images.githubusercontent.com/75293860/105848861-33e7bd80-5fa5-11eb-88d8-888f5ff23982.png)
  - Rosewood
![rosewood_planks](https://user-images.githubusercontent.com/75293860/105848872-364a1780-5fa5-11eb-8e2e-6266b6202feb.png)
  - Yucca
![yucca_planks](https://user-images.githubusercontent.com/75293860/105848881-3813db00-5fa5-11eb-9a8e-0d6b4d3d42b9.png)

- [Autumnity](https://www.curseforge.com/minecraft/mc-mods/autumnity)
  - Maple
![maple_planks](https://user-images.githubusercontent.com/75293860/105848889-3c3ff880-5fa5-11eb-8d99-e376b0bcc3d2.png)

- [Endergetic](https://www.curseforge.com/minecraft/mc-mods/endergetic)
  - Poise
![poise_planks](https://user-images.githubusercontent.com/75293860/105848893-3e09bc00-5fa5-11eb-8a63-d08d8d9d8829.png)

- [Upgrade Aquatic](https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic)
  - Driftwood
![driftwood_planks](https://user-images.githubusercontent.com/75293860/105848900-3fd37f80-5fa5-11eb-817c-49d6ff33e80b.png)
  - River
![river_planks](https://user-images.githubusercontent.com/75293860/105848906-419d4300-5fa5-11eb-98ab-e01d4063d066.png)

 
 - [Enhanced Mushrooms](https://www.curseforge.com/minecraft/mc-mods/enhanced-mushrooms) (Not technically made by TeamAbnormals, but they have similar quality standards and utilize AbnormalsCore
   - Red Mushroom
![red_mushroom_planks](https://user-images.githubusercontent.com/75293860/105848920-4661f700-5fa5-11eb-9fd3-0b3d0f9fac1e.png)
   - Brown Mushroom
![brown_mushroom_planks](https://user-images.githubusercontent.com/75293860/105848927-48c45100-5fa5-11eb-84e1-6b3bef956840.png)
   - Glowshroom (Note that these are transparent and glow)
![glowshroom_planks](https://user-images.githubusercontent.com/75293860/105848937-4b26ab00-5fa5-11eb-8838-88f70cb17c7f.png)

Hope that helps.

**Comment by 852DuartePls** [comment]
It's a good idea, I'll start working on it as soon as my exams are over
