### ISSUE TITLE
Suggestion - convert

### ISSUE THREAD

**Issue by zachsai** [852DuartePls/MoreCraftingTables#7]
![image](https://user-images.githubusercontent.com/63996164/159404434-191e6554-b707-4262-a3e0-b263f74a3f8a.png)
could you add recipe for all your crafting tables to convert them back into the default crafting table? This would help players if ever a mod didnt use forge tags in any case

**Comment by 852DuartePls** [comment]
Greetings, I am very sorry for the delay but it is a very good idea, and I have just implemented it. ;)
