### ISSUE TITLE
Missing crafting table variants for ancient and bamboo planks added by quark (1.19.2)

### ISSUE THREAD

**Issue by kmax2040** [852DuartePls/MoreCraftingTables#9]
Quark for 1.19.2 adds 4 wood types (excluding the colored planks) which are: blossom, azalea, ancient (found as a sapling in an ancient city chest), and bamboo (which is backported from minecraft 1.20). Currently only two of these are supported by the more crafting tables mod. I believe that the ancient and bamboo planks are disabled by default in the config so maybe that's why they were missed.

**Comment by 852DuartePls** [comment]
You're right, I totally overlooked it somehow, but I've already updated the mod and added them, thanks for noticing
